version: 2

jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.60
    environment:
      - working_directory: /home/circleci/repo
    steps:

      # checkout the repository
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "83:f5:c9:b8:20:88:a3:3e:47:19:ec:9e:76:d5:f1:23"
      # build with Hugo
      - run: HUGO_ENV=production hugo -v

      - run:
          name: push everything
          command: |
            git config user.email "${EMAIL}"
            git config user.name "${NAME}"
            git status
            git add -A
            git commit -m "[skip ci] built from circleci and pushed"
            git push -u origin master
